### PR TITLE
find templates with custom babel parser

### LINKED ISSUE #171: missing semicolon in class attributes breaks build
```
export default class McComponent extends Component<Signature> {
  x=6 // <- missing semi

  <template>
     ....
  </template>
```

### PR DESCRIPTION
**Pull request by patricklx**
i noticed that the current template parsing has issues.

I created a custom parser for babel which can parse the template tags.
https://babeljs.io/docs/babel-parser#will-the-babel-parser-support-a-plugin-system

I also added a conditional prefix to fix #171

### CODE REVIEW

**Comment by patricklx** [comment]
Will try with htmlparser2. No need for full spec compliance here. Better fast and forgiving :)

**Comment by patricklx** [comment]
this is ready now

**Comment by patricklx** [comment]
@rwjblue @chriskrycho

**Comment by dfreeman** [comment]
I'm not an active maintainer here or on Embroider, but my guess is that https://github.com/embroider-build/content-tag is a more complete solution to the issues you're aiming to tackle here.

**Comment by ef4** [comment]
Yes, that is correct and we hope that content-tag is the much more robust solution. It's rust compiled to wasm, based on SWC so it has the benefit of a full javascript parser.

The intention is to PR changes to ember-template-imports that would use content-tag to replace the preprocessor stage, and the babel stage here will also not be needed at all because babel-plugin-ember-template-compilation has already shipped the corresponding feature that goes with content-tag.

**Comment by patricklx** [comment]
What about other packages that depend on this to find the template parts? Like the eslint ember plugin. template lint etc.

**Comment by patricklx** [comment]
So, it is already in a state that can be used for this?

**Comment by patricklx** [comment]
content-tag does not look like its ready #182

**Comment by ef4** [comment]
Thanks for starting this work, I was able to extract a reproduction of the bug you found. https://github.com/embroider-build/content-tag/pull/16

**Comment by NullVoxPopuli** [comment]
gonna close this as
- bulk of the work was extracted to another project
- we have content-tag

thanks again for your hard work @patricklx, it's much appreciated!

**Pull request closed without merging**
