### PR TITLE
chore: converts util to typescript

### PR DESCRIPTION
**Pull request by gabrielcsapo**
# Summary

updates util to be util.ts and moves over code form https://github.com/ember-template-lint/ember-template-lint/blob/master/lib/extract-templates.js#L4 to be used in more libraries.

I met with @chriskrycho and @rwjblue to verify the types and get help with the ones that were not typed initially. THANK YOU!

> https://github.com/ember-template-imports/ember-template-imports/pull/77 must be merged first.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@chriskrycho I need your typescript expertise. Some of these types are extremely hard to track down, mind pairing on this tomorrow morning?

**Comment by rwjblue** [comment]
@gabrielcsapo - I merged #77, so I think this needs a quick rebase/fixup...

**Comment by gabrielcsapo** [comment]
@rwjblue rebased. Most likely this should be a minor release since most people access util through src and now it would be through lib.

**Comment by rwjblue** [comment]
Ultimately, I don't think we expect folks to use our internal `util` module (specifically we consider it private / internal API).

**Pull request merged**
