### PR TITLE
Embroider + HTMLBars 6 compatibility

### PR DESCRIPTION
**Pull request by dfreeman**
## Overview

This PR updates `ember-template-imports` to target the `precompileTemplate` macro as implemented in [`babel-plugin-ember-template-compilation`](https://github.com/emberjs/babel-plugin-ember-template-compilation). This makes this addon compatible with `ember-cli-htmlbars` 6, as well as Embroider, fixing #12.

With the introduction of `precompileTemplate` as a standard, composable way for addons to hook into template precompilation, the rest of the ecosystem no longer needs special knowledge of `ember-template-imports` baked into it. Accordingly, a big part of this PR is importing code (in particular from `babel-plugin-htmlbars-inline-precompile`) into this package to be self-managed.

## Details

This looks like a monstrous PR, but a fair amount of the diff is directly imported code that already existed elsewhere. Everything prior to e21ec6a is commits that were pulled from `babel-plugin-htmlbars-inline-precompile` directly. From there down, the commits are a series of mostly-small changes to integrate that code into `ember-template-imports` and then update it to handle the new compilation target.

These commits should be individually pretty consumable, but feel free to ping me here or on Discord if something's unclear.

## Compatibility
This is a breaking change. It requires `ember-cli-htmlbars` >= 6.0 and `ember-source` >= 3.27.0 in order for the host to use the `ember-template-compilation` Babel plugin that provides support for `precompileTemplate`. It also drops support for Node 10, which is EOL.

## Cleanup
This PR aims to alter as little as possible about the overall flow of template processing from the status quo to aid in reviewing, but there are definitely some clear follow-on steps that could be taken (by me, or by anyone else interested). In no particular order...

### TypeScript
The existing code in `babel-plugin-htmlbars-inline-precompile` was a mix of JS and TS. With the aim of changing as little as possible in this first pass, I bootstrapped TypeScript in this package but otherwise did no conversion. Moving the build code to be either all TS or all JS would likely lead to a smoother DX for future contributors.

### Processing Flow
Currently a fair amount of processing takes place as string manipulation on source files to support both the `hbs` tagged strings and `<template>` tag form factors.

Really the _only_ thing that needs to happen as string manipulation is converting `<template>` into something Babel can parse—everything else (including 100% of the `hbs` form factor processing) could be done in structured AST transforms to avoid potential issues with name clashes and the like.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Need webpack as well?

**Comment by dfreeman** [comment]
That was only one of about 100 different CI issues I was juggling.

**Comment by chriskrycho** [comment]
Just tested this out on LinkedIn's biggest app, which includes use of yarn workspaces, and it's working! 🎉 Thanks, @dfreeman!

**Comment by NullVoxPopuli** [comment]
Because this now runs before babel, does that mean it should work with typescript?

**Comment by NullVoxPopuli** [comment]
I just tried this branch on an ember 4.2-alpha, embroider, monorepo app, and got this error:

<details><summary>the error</summary>

```

=================================================================================

ENV Summary:

  TIME: Tue Dec 07 2021 17:33:00 GMT-0500 (Eastern Standard Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/16.13.0/bin/node
  - /✂️/limber/frontend/node_modules/.bin/ember
  - serve
  - -p
  - 4201
  EXEC_PATH: 🏠/.volta/tools/image/node/16.13.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /tmp/yarn--1638916379783-0.7955584898967099
  - /✂️/limber/frontend/node_modules/.bin
  - 🏠/.config/yarn/link/node_modules/.bin
  - /✂️/limber/node_modules/.bin
  - 🏠/.yarn/bin
  - 🏠/.volta/tools/image/node/16.13.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - 🏠/.volta/tools/image/node/16.13.0/lib/node_modules/npm/bin/node-gyp-bin
  - 🏠/.volta/tools/image/node/16.13.0/bin/node_modules/npm/bin/node-gyp-bin
  - 🏠/.volta/tools/image/npm/8.1.3/bin
  - 🏠/.volta/tools/image/yarn/1.22.17/bin
  - 🏠/.volta/tools/image/node/16.13.0/bin
  - /tmp/frum_27237_1638915700932/bin
  - 🏠/Applications/frum
  - 🏠/.volta/bin
  - 🏠/.pythons/Python-3.6.3/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - /tmp/frum_5793_1638912464527/bin
  - 🏠/Applications/frum
  - 🏠/.volta/bin
  - 🏠/.pythons/Python-3.6.3/bin
  - 🏠/.cargo/bin
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /snap/bin
  - 🏠/.fzf/bin
  PLATFORM: linux x64
  FREEMEM: 17902690304
  TOTALMEM: 33442091008
  UPTIME: 3931.16
  LOADAVG: 1.71,1.64,1.41
  CPUS:
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 3104
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2599
  - 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz - 2400
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.17.2
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 6.0.4
  - modules: 93
  - napi: 8
  - nghttp2: 1.45.1
  - nghttp3: 0.1.0-DEV
  - ngtcp2: 0.1.0-DEV
  - node: 16.13.0
  - openssl: 1.1.1l+quic
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 9.4.146.19-node.13
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: MODULE_NOT_FOUND
  - codeFrame: [undefined]
  - errorMessage: Cannot find module '../lib/preprocess-embedded-templates'
Require stack:
- /✂️/limber/frontend/node_modules/ember-template-imports/src/preprocessor-plugin.js
- /✂️/limber/frontend/node_modules/ember-template-imports/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/project.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/get-config.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/instrumentation.js
- /✂️/limber/node_modules/ember-cli/lib/cli/index.js
- /✂️/limber/node_modules/ember-cli/bin/ember
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Cannot find module '../lib/preprocess-embedded-templates'
Require stack:
- /✂️/limber/frontend/node_modules/ember-template-imports/src/preprocessor-plugin.js
- /✂️/limber/frontend/node_modules/ember-template-imports/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/project.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/get-config.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/instrumentation.js
- /✂️/limber/node_modules/ember-cli/lib/cli/index.js
- /✂️/limber/node_modules/ember-cli/bin/ember
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Cannot find module '../lib/preprocess-embedded-templates'
Require stack:
- /✂️/limber/frontend/node_modules/ember-template-imports/src/preprocessor-plugin.js
- /✂️/limber/frontend/node_modules/ember-template-imports/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /✂️/limber/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /✂️/limber/node_modules/ember-cli/lib/models/project.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/get-config.js
- /✂️/limber/node_modules/ember-cli/lib/utilities/instrumentation.js
- /✂️/limber/node_modules/ember-cli/lib/cli/index.js
- /✂️/limber/node_modules/ember-cli/bin/ember
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/✂️/limber/frontend/node_modules/ember-template-imports/src/preprocessor-plugin.js:5:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

=================================================================================
```

</details>

**Comment by chriskrycho** [comment]
@NullVoxPopuli ah, it has a build step. It's *good* that you're seeing that; it means it didn't silently swallow the error. For anyone who wants to test this:

- clone the repo
- check out this branch
- run `yarn`
- run `yarn pack` and grab the path to the `.tgz` it produces
- in the `package.json` for the app/addon you're testing in, do `"ember-template-imports": "<path to tgz from previous step>"`

To your other question: it looks like this doesn't change the (lack of) support for `.gts` files.

**Comment by chriskrycho** [comment]
Correction: it *does* work with TS (`.gts`) now, as long as your Babel config otherwise supports (most easily, just installing `ember-cli-typescript` alongside this works). Obviously there are still gaps here—type checking will require Glint, etc.—but it *compiles*. I was misled by configuration mistakes and type errors previously. 😉

**Comment by NullVoxPopuli** [comment]
Just tested this in a small app, and it appears to work (with gts!)
I even forgot to add
```js
import { on } from '@ember/modifier';
```
to the top of my component :upside_down_face: 

what else can I do to help get this released?

**Comment by dfreeman** [comment]
Since this seems to be passing muster in a couple real-world apps, I've merged this and hopefully someone with publish access can get it out the door soon 🙂

**Comment by ef4** [comment]
Yay, so glad to see this, thanks @defreeman.

**Pull request merged**
