### PR TITLE
Do not add the babel plugin if it's already present

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Resolves: https://github.com/ember-template-imports/ember-template-imports/issues/28

### CODE REVIEW

**Comment by dfreeman** [comment]
This seems like it may be papering over some other bug 🤔 

Is `included` being invoked more than once for the same parent app/addon somehow?

**Comment by NullVoxPopuli** [comment]
yeah, the app has a direct dependency on the addon, as well as several other addons that are direct dependencies (but have the addon with template imports as a dependency)

**Comment by chriskrycho** [comment]
Minimally you should emit a warning here (in the same way we do with the various class properties plug-ins).

**Comment by NullVoxPopuli** [comment]
would the warning be actionable?

**Comment by dfreeman** [comment]
> yeah, the app has a direct dependency on the addon, as well as several other addons that are direct dependencies (but have the addon with template imports as a dependency)

This is exactly my point 🙂 

The app has a direct dependency on the addon -> `included(theApp)`
Several other addons have template-imports as a dependency -> `included(theAddon)`

It shouldn't ever be the case that `included` is called twice on the same parent, unless something elsewhere isn't working as it should be.

**Comment by NullVoxPopuli** [comment]
I don't understand though.... what's wrong? what's the path forward?
is ember-cli broken?
It's not unreasonable that multiple entries in a dependency tree would reference the same addon..

**Comment by dfreeman** [comment]
> It's not unreasonable that multiple entries in a dependency tree would reference the same addon..

Exactly! That's precisely the point of the hook. For each node (app or addon) in the tree that relies on a given addon, that addon's `included` hook should be invoked _once_ to inform the addon that it's acting as a dependency of the `includer` in question.

Given a structure like this:

```
my-app
├─ addon-a
├─ addon-b
│  ├─ addon-a
```

Then `addon-a` should have its `included` hook invoked twice: once with `my-app` as the includer and once with `addon-b` as the includer. This gives it the opportunity to inspect and tweak each member of the project that depends on it individually.

> what's wrong? what's the path forward? is ember-cli broken?

That's what I'm trying to get to the bottom of 🙂 

_Something_ definitely isn't working as expected, and from the information we have so far it's not clear if that something is `ember-cli`, `ember-template-imports`, or some unique element of your project setup.

If you're not able to diagnose that yourself, then I think a useful next step would be a reproduction so that others can take a look and try to work out what's going on.

**Comment by NullVoxPopuli** [comment]
> If you're not able to diagnose that yourself, then I think a useful next step would be a reproduction so that others can take a look and try to work out what's going on.

excellent! (I'm already half way through creating a reproduction).

**Comment by NullVoxPopuli** [comment]
ok, here is my reproduction: https://github.com/NullVoxPopuli/monorepo-babel-plugin-reproduction-template-imports

it seems to _only_ occur with typescript. idk if that makes sense, but before I added `enableTypeScriptTransform: true` to all the addons in the repro-repo, things work as expected! :tada:

**Comment by NullVoxPopuli** [comment]
I had thought it was maybe due to aggressive cacheKeyForTree usage, but that wasn't it (I commented it out)

**Comment by dfreeman** [comment]
Thanks, that reproduction was useful! It looks like `enableTypeScriptTransform` (and probably some other `ember-cli-babel` options), due to the internals of how `ember-cli-babel` manages plugins, to wind up sharing a `plugins` array across separate instances of a given addon.

So we're getting a unique `includer` each time `included` is called, but `includer.options.babel.plugins` winds up being the same array for every instance of e.g. `addon-a`. While I don't think this is probably ideal behavior in `ember-cli-babel`, I think the same issue could arise from an addon manually setting plugins in the prototype object it exports in `index.js`.

Given that, this guard is probably reasonable to add. Thanks for helping track down the root cause!

**Review by dfreeman — APPROVED** [review]

**Comment by NullVoxPopuli** [comment]
should we still add a warning? what would it say?

**Comment by dfreeman** [comment]
I don't _think_ we need a warning, since the situation this arises in isn't the result of misconfiguration on the user's part.

But @chriskrycho if you disagree I'm happy to defer to you 😄

**Comment by chriskrycho** [comment]
Nope, I think it’s reasonable!

**Pull request merged**
