### PR TITLE
bug: when using a generic named `template` in `.gts` files (e.g. `type template = { foo: string }; Partial<template>;`)

### PR DESCRIPTION
**Pull request by gabrielcsapo**
# Summary

Showcases issue with parsing type template with the current regex parsing.

### CODE REVIEW

**Comment by rwjblue** [comment]
Discussed this briefly with @chriskrycho earlier today. The rough conclusion here is that we really need a proper parser that is context aware. At the moment we have a few options (maybe want to do multiple?):

1. provide an `eslint` rule that can be used to help folks avoid this specific pattern
2. update our regexp matching to require a whitespace before `<template>` (this would cause `Partial<template>` to not match) -- This is only a stop gap solution (in TS `Partial <template>` is still valid AFAICT), but might be "good enough" as a temporary haxxors to prevent trolling folks...
3. write a "real" context aware parser

**Comment by chadhietala** [comment]
Can't you just use the TypeScript parser? It thinks everything is JSX. I believe you could at least use it to get the correct line and cols to pull out `<template>`. Probably needs to 

https://astexplorer.net/#/gist/d241bdc99c90e827b3a70e8307db6eca/ba2e42b08f514e42e76f13162b1046fdf9fdc49f

**Comment by chriskrycho** [comment]
That's a really good idea; it totally barfs on the internals but that's perfectly fine for our purposes, and it even handles the "default export" syntax, and potential future extensions we've discussed like the `type:signature=` extension: https://astexplorer.net/#/gist/7e41c823a8d3b7eb3cf490364b5c8606/1f1de18cdbf4035c928bfd0921cc861d9a647a3f

**Comment by dfreeman** [comment]
That's a createive idea, but I'm not sure it handles class-embedded templates in a way that's workable for us. This:

```tsx
class MyComponent {
  <template>Hello, world</template>
}
```

Ends up parsing as a `ClassDeclaration` followed by an `ExpressionStatement`. The parser's error recovery is kicking in and saying "oh, this isn't a legal place for a JSX expression; you must have forgotten the `}` from that class" and automatically inserting it, then subsequently ignoring the class's intended `}` as errant punctuation.

The problem becomes clearer if you have members after the `<template>`:

```tsx
class MyComponent {
  <template>Hello, world</template>

  method() {
    console.log('hi');
  }
}
```

That's parsed as a series of four statements:
 -  `ClassDeclaration`: `class MyComponent {}`
 - `ExpressionStatement`: `<template>Hello, world</template>`
 - `ExpressionStatement`: `method()`
 - `Block`: `{ console.log('hi') }`

https://astexplorer.net/#/gist/7e41c823a8d3b7eb3cf490364b5c8606/latest

You can look at the `parseDiagnostics` key on `SourceFile` to see the error recovery steps it's taking to wind up at that structure.

**Comment by dfreeman** [comment]
> update our regexp matching to require a whitespace before `<template>`

Could we instead validate that a `<template>` _isn't_ preceded by something like `\w+[ ]*`? In general I think expressions, statements and class members are always going to have to be separated by some kind of punctuation or a newline, so if we see an identifier[^1] (with or without a space) before `<template>`, that may be enough for us to know it's not the start of an embedded template.

For the record, I absolutely agree that the "right" answer here is an actual parser that understands both ES/TS syntax and our `<template>` embedding rules, but I'm wary of the cost of actually building and maintaining something like that, so I'm pretty motivated to find "good enough" solutions for this kind of thing if they exist.

[^1]: I know `\w+` isn't a proper regex for matching an ES identifier, but here it may be close enough for jazz.

**Comment by chriskrycho** [comment]
Drat, good find. Would have been nice if that hack worked.

A slightly smarter regex seems nice if we can make it work, but I also am just not especially worried about this case. A lint rule is *more* than sufficient here.

I have never – literally *not even once* – seen a lowercase name used for a type parameter, in the 6 years I have been writing TypeScript full time. I have seen `Array<T>` (idiomatic TS), `Array<A>` (Haskellers and the like), `Array<Item>` and `Map<Key, Value>` (Swift people), `Array<TItem>` and `Map<TKey, TItem>` (C♯ people), and many other variants, but literally never anything like `Partial<template>`. I don't doubt someone somewhere has written it, but it’s rather unlikely to show up in real world code, and we can (and should!) ship a lint rule that is on by default and an error, not a warning, for this specific case if we want. It can just use the `@typescript-eslint/naming-convention` rule (customized if we so desire).

**Comment by chadhietala** [comment]
I can buy that.

**Pull request closed without merging**
